config/routes.rb
Bunny::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get '/home', to:"restaurants#home"
  get "log_in" => "sessions#new", :as => "log_in"
get "log_out" => "sessions#destroy", :as => "log_out"
resources :sessions
  get "sign_up" => "users#new", :as => "sign_up"
root :to => "restaurants#index" # remove ./public/index.html
resources :users
  resources :customers

  resources :menus

  resources :items do
  resources :menus
end

  resources :locations

  resources :restaurants do
   resources :menus
 end

  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
belongs_to :restaurant
belongs_to :item
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:restaurant_id, :item_id, :price)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
<%= link_to 'Home', '/home', id: "logo" %>
<%= link_to 'Item', items_path, id: "logo" %>
<h3><% if current_user %>
Logged in as <%= current_user.email %>
<%= link_to "Log out", log_out_path, id: "log" %></h3>
<% else %>
<%= link_to "Sign up", sign_up_path, id: "logo" %> or
<%= link_to "Log in", log_in_path, id: "logo" %>
<% end %>
</header>
<br>
<h4>Listing menus</h4>

<table>
  <thead>
    <tr>
      <th>Rid&nbsp&nbsp</th>
      <th>Itemid&nbsp&nbsp</th>
      <th>Price&nbsp&nbsp</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.restaurant_id %></td>
        <td><%= menu.item_id %></td>
        <td><%= menu.price %></td>
        <td><%= link_to 'Show', menu %> </td>
        <!--<td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rid:</strong>
  <%= @menu.restaurant_id %>
</p>

<p>
  <strong>Itemid:</strong>
  <%= @menu.item_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>