config/routes.rb
Bunny::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get '/home', to:"restaurants#home"
  get "log_in" => "sessions#new", :as => "log_in"
get "log_out" => "sessions#destroy", :as => "log_out"
resources :sessions
  get "sign_up" => "users#new", :as => "sign_up"
root :to => "restaurants#index" # remove ./public/index.html
resources :users
  resources :customers

  resources :menus

  resources :items do
  resources :menus
end

  resources :locations

  resources :restaurants do
   resources :menus
 end

  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
has_one :location
has_many :menus, dependent: :destroy
has_many :items, :through => :menus
#def self.query(query)
    # where(:title, query) -> This would return an exact match of the query
    #binding.pry
    #Restaurant.joins(:location).where("locations.zip = ?", "%#{query}")
    #where("rating like ?", "%#{query}%")

    #Restaurant.find_by_sql("SELECT * from restaurants INNER JOIN locations ON restaurants.id = locations.restaurant_id where locations.zip = '87102' ") 
  #end 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  #def index
     #if params[:search]
      #@restaurants = Restaurant.search(params[:search]).order("created_at DESC")
    #else
      #@restaurants = Restaurant.order("created_at DESC")
  #end
#end

def index
    if params[:search]
      locations = Location.where("zip = ?", params[:search])
      @restaurants = Restaurant.where(id: locations.pluck(:restaurant_id))
    
    else
      @restaurants = Restaurant.all
    end
end



  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end


  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end
  
  
  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:rid, :rname, :phno, :delivery, :rating, :timings, :category)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rid %><br>
    <%= f.number_field :rid %>
  </div>
  <div class="field">
    <%= f.label :rname %><br>
    <%= f.text_field :rname %>
  </div>
  <div class="field">
    <%= f.label :phno %><br>
    <%= f.text_field :phno %>
  </div>
  <div class="field">
    <%= f.label :delivery %><br>
    <%= f.text_field :delivery %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :timings %><br>
    <%= f.text_field :timings %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/home.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
<%= link_to 'Sign up', sign_up_path, id: "logo" %>
<%= link_to 'Log in', log_in_path, id: "logo" %>
</div>
</header><br><br>
<h1>Tinnara</h1>
<h2>- A Restaurant Suggestion App</h2>
<p>
  
</p>

app/views/restaurants/index.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
<%= link_to 'Home', '/home', id: "logo" %>
<%= link_to 'Item', items_path, id: "logo" %>
<h3><% if current_user %>
Logged in as <%= current_user.email %>
<%= link_to "Log out", log_out_path, id: "log" %>
<% else %>
<%= link_to "Sign up", sign_up_path, id: "logo" %> 
<%= link_to "Log in", log_in_path, id: "logo" %></h3>
<% end %>
</header>
<br><br>
<head>
  <title>Simple Search Form</title>
</head>
<body>
  <%= form_tag(restaurants_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="right">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Nearby Restaurants" %>
      <button class="btn" type="submit"><i class="icon-search">Submit</i></button>
    </div>
<% end %>
 
<h4>List of restaurants</h4>
<table>
<table id="myTable" class="tablesorter tablesorter-blue">
  <thead>
    <tr>
      <th>S.No</th>
      <th>Restaurant Name</th>
      <!--<th>Phno</th>
      <th>Delivery</th>-->
      <th data-sorter="true">Rating</th>
      <!--<th>Timings</th>
      <th>Category</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.rid %></td>
        <td><%= restaurant.rname %>&nbsp&nbsp&nbsp</td>
        <!--<td><%= restaurant.phno %></td>
        <td><%= restaurant.delivery %></td>-->
        <td><%= restaurant.rating %></td>
        <!--<td><%= restaurant.timings %></td>
        <td><%= restaurant.category %></td>-->
        <td><%= link_to 'Show', restaurant %></td>
        <!--<td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<!--<%= link_to 'New Restaurant', new_restaurant_path %>-->

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
<%= link_to 'Home', '/home', id: "logo" %>
<%= link_to 'Restaurant', restaurants_path, id: "logo" %>
<h3><% if current_user %>
Logged in as <%= current_user.email %>
<%= link_to "Log out", log_out_path, id: "log" %></h3>
<% else %>
<h3><%= link_to "Sign up", sign_up_path, id: "log" %> 
<%= link_to "Log in", log_in_path, id: "log" %></h3>
<% end %>
</header>
<br>


<p id="notice"><%= notice %></p>

<p>
  <strong>Rid:</strong>
  <%= @restaurant.rid %>
</p>

<p>
  <strong>Rname:</strong>
  <%= @restaurant.rname %>
</p>

<p>
  <strong>Phno:</strong>
  <%= @restaurant.phno %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @restaurant.delivery %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @restaurant.rating %>
</p>

<p>
  <strong>Timings:</strong>
  <%= @restaurant.timings %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p><br>

<h4>Items</h4>
<div id="items">
  <%  @restaurant.items.each do |item| %>
  <%= div_for item do %>
  <p>
   <%= h(item.iname) %>
 </p>
<% end %>
<% end %>

<!--<h4>menus</h4>-->
<div id="menus">
  <%  @restaurant.menus.each do |menu| %>
  <%= div_for menu do %>
  <p>
   <%= h(menu.price) %>
 </p>

<% end %>
<% end %>

</div>
</div>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>